name: parking_spot_saver
description: A Flutter app to save and navigate back to your parked car location.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  flutter_polyline_points: ^3.0.1
  geolocator_platform_interface: ^4.0.7
  dio: ^5.3.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  device_preview: ^1.1.0

flutter:
  uses-material-design: true